import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer/Footer";
import NavBar from "@/components/navBar/NavBar";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Nekode',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
      <NavBar/>
      {children}
      <Footer/>
      </body>
    </html>
  )
}
