version: '3'

services:
  nestapp:
    container_name: nestapp
    image: oktubre77/nestapp:1.0.0
    build: .
    ports: 
      - '5000:5000'
    environment:
      - DB_TYPE=postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=db
      - PORT=5000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - db
  db:
    image: postgres:14.3
    restart: always
    ports:  
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    container_name: db
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
